#!/usr/bin/env  python3

from datetime import date, timedelta
from math import ceil

start = date(2025, 3, 24)
today = date.today()
end = date(2025, 5, 29)

one_day = timedelta(days=1)

total_duration = (end-start+one_day).days
current_duration = (today-start+one_day).days

course_date_progress = current_duration / total_duration

total = 122 - 4 # 4 phantom assignments for some reason
current = int(input("How many assignments have you completed so far? "))

current_pace = current / current_duration
expected_pace = course_date_progress * total / current_duration

wanted_days_ahead = 5

print("Current pace:", current_pace, "assignments per day.")
print("AKA", current*(total_duration/total)-current_duration, "days ahead of schedule")
print("Expected pace:", expected_pace, "assignments per day.")
print()
print("To do today:", ceil(max((expected_pace - current_pace) * current_duration + min(wanted_days_ahead, total_duration-current_duration) * expected_pace, 0)), f"assignments (to get {wanted_days_ahead} days ahead).")
print("Pace required to meet goal:", (total - current) / (total_duration - current_duration), "assignments per day.")
