#!/usr/bin/env  python3

from datetime import date, timedelta

start = date(2025, 3, 24)
today = date.today()
end = date(2025, 5, 29)

one_day = timedelta(days=1)

total_duration = (end-start+one_day).days
current_duration = (today-start+one_day).days

course_date_progress = current_duration / total_duration

total = 110
current = int(input("How many assignments have you completed so far? "))

current_pace = current / current_duration
expected_pace = course_date_progress * total

print("Current pace:", current_pace, "assignments per day.")
print("AKA", current*(total_duration/total), "days")
print("Expected pace:", expected_pace, "assignments per day.")
print()
print("To do today:", max(expected_pace-current_pace, 0), "assignments.")
print("Pace required to meet goal:", (total - current) / (total_duration - current_duration), "assignments per day.")
