# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Should help performance when swapping
  boot.kernel.mg-lru.enable = true;

  # Reduce swapping
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9553b2d4-6ed3-48ff-9cbc-aaf0109b185d";
    fsType = "ext4";
    # This is a slow HDD...
    options = [ "noatime" ];
  };

  boot.initrd.luks.devices."nixos" = {
    device = "/dev/disk/by-uuid/4b25efe2-6f13-42a7-8d27-3ab1f45abbaa";
    preLVM = true;
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/0395f3bb-16dc-4768-87ee-7aa5eb28ab3e"; }
  ];

  fileSystems."/var/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "size=4G" ];
  };

  boot.tmp = {
    useTmpfs = true;
    tmpfsSize = "300%";
    cleanOnBoot = true;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
