{
  pkgs,
  self,
  narser,
  ce-programs,
  ...
}:
{
  home.packages = with pkgs; [
    baobab
    bluetuith
    cachix
    ce-programs.legacyPackages.${system}.cemu-ti
    jmtpfs
    narser.packages.${system}.default
    ce-programs.legacyPackages.${system}.tilp2
    wf-recorder
  ];
}
