# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Should help performance when swapping
  boot.kernel.mg-lru.enable = true;

  # Reduse swapping
  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/49af3e55-9340-4b06-bcd7-9a322c7d92c4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."nixos" = {
    device = "/dev/disk/by-uuid/031e37e6-c637-4692-a5e8-fdce224ff647";
    preLVM = false;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8022-283B";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "size=8G" ];
  };

  boot.tmp = {
    useTmpfs = true;
    tmpfsSize = "600%"; # Linux kernel smh
    cleanOnBoot = true;
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 32 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
